experiments:
- name: cifar10_resnet8_lr5e_neg05_gs7
  num_clients: 40
  rounds: 200
  epochs: 2
  gossip_steps: 7
  lr: 5.0e-05
  lr_schedule: false
  batch_size: 128
  client_parallelism: 4
  methods:
  - max_degree
  optimizer: sgd
  ssos_enabled: false
